name: Video Pro
slug: video-pro
groups: pro
form:
  general:
    - name : video_fg_text
      label: Video
      type: fields-group
      status: open
      schema:
        
        - name: link_type
          label: Video Type
          type: select
          value: link
          options:
            link: Link
            custom: Custom
            
        - name: video_link
          label: Video Embed Url
          type: text 
          value: https://www.youtube-nocookie.com/embed/YE7VzlLtp-4?autoplay=0&amp;showinfo=0&amp;rel=0&amp;modestbranding=1&amp;playsinline=1
          help: hints: add `?controls=0` at the end of youtube embed video link to hide controls
          depends: 
            link_type: link

        - name: custom_video
          label : Select Video
          type: media
          filters: video
          depends: 
            link_type: custom
            
        - name: video_poster
          type: media
          filters: image, unsplash
          value: 'libraries/quix/assets/images/placeholder.png'
          depends: 
            link_type: custom

        - name : controls
          type : switch
          value: true
          depends:
            link_type: custom

        - name : autoplay
          type : switch
          value: true

        - name : mute
          type : switch
          value: false
        
        - name : loop
          type : switch
          value: true
          depends:
            link_type: custom
            
        - name: enable_overlay
          type: switch
          label: Video Overlay
          value: false

        - name: overlay_img
          type: media
          label: Overlay Image
          help: Preview image
          filters: image
          value: libraries/quix/assets/images/placeholder.png
          depends:
            enable_overlay: true

        - name: play_icon
          lable: Play Icon
          type: switch
          value: false
          help: Enbale the overlay image at first
          depends:
            enable_overlay: true          

        - name: upload_Picon
          type: media
          label: Upload Icon
          value: libraries/quix/assets/images/placeholder.png
          depends:
            play_icon: true                       


  styles:
    - name    : text_fields_group
      label   : Style
      type    : fields-group
      status  : open
      schema  :
        - name : alignment
          type : choose
          responsive : true
          options:
            left :
              label: Left
              icon : qxuicon-align-left
            center :
              label : Center
              icon : qxuicon-align-center
            right : 
              label : Right
              icon : qxuicon-align-right
        
        - name : height
          type : slider
          defaultUnit: px
          max: 1000
          value: 
            desktop : 450
            tablet : 350
            phone : 250
        
        - name : width
          type : slider
          defaultUnit: %
          max: 1000
          value: 
            desktop : 100
            tablet : 100
            phone : 100

