name: Media Carousel
slug: media-carousel
groups: pro
form:
  general:
    - name : media-carousel-fg_element
      label: Images
      type: group-repeater
      schema:
        - name: title
          value: Sample Image

        - name: image
          type: media
          filters: image
          value: 'libraries/quix/assets/images/placeholder.png'

        - name: alt_text
          label : Alt Text
          type: text
          help : Google focuses on alt text when trying to understand what an image is about. So it's valuable for SEO, in addition to being useful for users.
          depends:
            image: '*'

        - name: caption
          type: text
          depends:
            image: '*'
            
        - name: link
          label: Link Url
          type: link
      value:
        - title: Title 1
          image: 'libraries/quix/assets/images/placeholder.png'
        - title: Title 2
          image: 'libraries/quix/assets/images/placeholder.png'
        - title: Title 3
          image: 'libraries/quix/assets/images/placeholder.png'
        - title: Title 4
          image: 'libraries/quix/assets/images/placeholder.png'
        - title: Title 5
          image: 'libraries/quix/assets/images/placeholder.png'

    - name    : media-carousel-fg_options
      label   : Columns
      type    : fields-group
      schema  :
        - name : column
          label: Column
          type : select
          value: 3
          options:
            1 : 1
            2 : 2
            3 : 3
            4 : 4
            5 : 5
            6 : 6

        - name : overlay
          label: Overlay
          type : select
          value: 'none'
          options:
            'none' : 'None'
            'text' : 'Text'

        - name : overlay_animation
          label: Overlay Animation
          type : select
          value: fade
          depends:
            overlay: 'text'
          options:
            'fade' : 'Fade'
            'slide-top' : 'Slide Top'
            'slide-right' : 'Slide Right'
            'slide-bottom' : 'Slide Bottom'
            'slide-left' : 'Slide Left'

        - name : show_title
          label: Show Title
          type : switch
          value: true

        - name : caption
          label: Caption
          type : switch
          value: true



    - name    : height-fg_options
      label   : Height
      type    : fields-group
      schema  :
        - name : height_option
          label: Height
          type : select
          value: 'default'
          options:
            'default' : 'Default'
            'custom-height' : 'Custom Height'

        - name  : image_height
          label : Height
          type: slider
          defaultUnit: 'px'
          units : 'px'
          depends:
            height_option: 'custom-height'
          max : 1000
          value:
            desktop : 70
            tablet : 50
            phone : 50

        - name : image_mood
          label: Image Mode
          depends:
            height_option: 'custom-height'
          type : select
          value: 'none'
          options:
            'contain' : 'Contain'
            'cover' : 'Cover'
            'fill' : 'Fill'
            'scale-down' : 'Scale Down'
            'unset' : 'Unset'
            'none' : 'None'

    - name    : media-carousel-navigation_style
      label   : Navigation
      type    : fields-group
      schema  :
        - name : show_arrow_navigation
          label: Show Arrow Navigation
          type : switch
          value: true

        - name : arrow
          label: Arrow
          type : select
          value: in
          depends:
            show_arrow_navigation: true
          options:
            in : Inside
            out : Outside

        - name : show_dot_navigation
          label: Show Dot Navigation
          type : switch
          value: true

        - name: bar_navigation
          label: Enable Bar Nav
          type: switch
          value: false
        
        - name: bar_vertical
          label: For Vertical
          type: switch
          value: false
          depends:
            bar_navigation: true           

        - name : barNav_position
          label: Position
          type : select
          value: 'bottom-center'
          options:
            'top-left' : 'Top Left'
            'top-right' : 'Top Right'
            'center-left' : 'Center Left'
            'center-right' : 'Center Right'
            'bottom-left' : 'Bottom Left'
            'bottom-center' : 'Bottom Center'
            'bottom-right' : 'Bottom Right'
          depends:
            bar_navigation: true

        - name : barNav_margin
          label: Margin
          type : select
          value: 'medium'
          options:
            'none' : 'None'
            'small' : 'Small'
            'medium' : 'Medium'
            'large' : 'Large'
          depends:
            bar_navigation: true          
    
    - name    : height-fg_behaviour
      label   : Behaviour
      type    : fields-group
      schema  :
        - name: pause_on_hover
          label: Pause on Hover
          type: switch
          value: true

        - name : auto_play
          label: Auto Play
          type : switch
          value: true

        - name: autoplay_speed
          label: Autoplay Speed ( MS )
          type: text
          value: 5000
          depends:
            auto_play: true

        - name: infinite_loop
          label: Infinite Loop
          type: switch
          value: false

        - name : set
          label: Slide as a Set
          type : switch
          value: false

  styles:
    - name    : media-carousel-fg_style
      label   : Image
      type    : fields-group
      status  : open
      schema  :
        
        - name : image_alignment
          label: Alignment
          type : choose
          responsive : false
          value: center
          options:
            left :
              label: Left
              icon : qxuicon-align-left
            center :
              label : Center
              icon : qxuicon-align-center
            right : 
              label : Right
              icon : qxuicon-align-right


        - name: overlay_color
          label: Overlay Color
          type: color
          value: rgba(0, 0, 0, 0.4)

        - name: border_divider
          type: divider
          label: Border

        - name : image_border
          label : Border
          type: border

        - name: padding_divider
          type: divider
          label: Padding

        - name  : image_spacing
          label : Spacing
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 15
            tablet : 15
            phone : 10

    - name    : image-title-fg_style
      label   : Title
      type    : fields-group
      schema  :
        - name: title_color
          label: Color
          type: color
          value: rgba(0, 0, 0, 1)

        - name: typo_divider
          type: divider
          label: Border

        - name: title_font
          label: Font
          type: typography

    - name    : navigation-fg_style
      label   : Navigation
      type    : fields-group
      schema  :
        - name: arrow_color
          label: Arrow Color
          type: color
          value: rgba(102, 102, 102, 0.6)

        - name  : arrow_size
          label : Arrow Size
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 25
            tablet : 25
            phone : 20

        - name: dot_divider
          type: divider
          label: Dot

        - name: dot_color
          label: Dot Color
          type: color
          value: rgba(238, 238, 238, 1)

        - name: dot_active_color
          label: Dot Active Color
          type: color
          value: rgba(102, 102, 102, 0.6)

        - name  : dot_width
          label : Dot Width
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 15
            tablet : 15
            phone : 15

        - name  : dot_spacing
          label : Dot Spacing
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 12
            tablet : 12
            phone : 10

        - name  : dot_margin
          label : Dot Margin
          type: slider
          max : 100
          units: px
          defaultUnit: px
          value:
            desktop : 25
            tablet : 25
            phone : 20

    - name    : media_carousel_fg_bar-style
      label   : Bar Nav
      type    : fields-group
      status  : close
      schema  :
        - name: bar_divider
          type: divider
          label: Bar

        - name: bar_color
          label: Bar Color
          type: color
          value: rgba(238, 238, 238, 1)

        - name: bar_active_color
          label: Bar Active Color
          type: color
          value: rgba(102, 102, 102, 0.6)   

        - name  : bar_width
          label : Bar Width
          type: slider
          max : 100
          units: px
          help: Hint: Height for Vartical bar
          defaultUnit: px
          value:
            desktop : 25
            tablet : 25
            phone : 25

        - name  : barActive_width
          label : Bar Active Width
          type: slider
          max : 100
          units: px
          help: Hint: Width (Active) for Vartical bar
          defaultUnit: px         

        - name  : bar_height
          label : Bar Height
          type: slider
          max : 100
          units: px
          help: Hint: Width for Vartical bar
          defaultUnit: px
          value:
            desktop : 5
            tablet : 5
            phone : 5

        - name  : barActive_height
          label : Bar Active Height
          type: slider
          max : 100
          units: px
          help: Hint: Height (Active) for Vartical bar
          defaultUnit: px            



