name: Testimonial Pro
slug: testimonial-pro
groups: content
form:
  general:
    - name: testimonials
      type: group-repeater
      schema: 
        - name: name
          value: John Doe

        - name: company
          help: Put designation and company name here. Eg, Creative Director, ThemeXpert 
          label: Job Title, Company Name

        - name: image
          type: file-manager

        - name: testimony
          type: editor
          value: Lorem ipsum dolor sit amet timeam deleniti mnesarchum ex sed alii hinc dolores ad cum. Urbanitas similique ex nam paulo temporibus ea vis id odio adhuc nostrum eos.
      value:
        - name: John Doe
          company: Creative Director, ThemeXpert
          testimony: Lorem ipsum dolor sit amet timeam deleniti mnesarchum ex sed alii hinc dolores ad cum. Urbanitas similique ex nam paulo temporibus ea vis id odio adhuc nostrum eos.
    
    - name: alignment
      type: select
      value: center
      label: Text Alignment
      image: true 
      responsive: true
      options:
        left: Left
        center: Center
        right: Right
    
    - name: arrows
      type: switch
      value: true
      help: This setting allows you to turn the navigation arrows on or off.

    - name: dots
      type: switch
      label: Dots Navigation 
      value: false
      help: Disabling this option will remove the circle button at the bottom of the slider.

    - name: autoplay
      type: switch
      labe: Auto Play
      help: If you would like the slider to slide automatically, without the visitor having to click the next button.

    - name: autoplay_speed
      type: text
      label: Autoplay Speed 
      value: 5000
      help: Autoplay Speed in milliseconds
      depends:
        autoplay: true        

    - name: name_tag
      type: select
      multiple: false
      label: Name Tag
      value: h4
      help: Default title Tag is h4
      options:
        h1: H1
        h2: H2
        h3: H3
        h4: H4
        h5: H5
        h6: H6
        p: p
        
  styles:
    - name : element_style
      type: divider
      label: Element Style - Apply On Element Body

    - name: bg_color
      type: color
      label: Background Color

    - name: margin
      type: margin
      value:
        top: 40px
        bottom: 40px
        left: 0px
        right: 0px

    - name: padding
      type: padding
      value:
        top: 0px
        bottom: 0px
        left: 40px
        right: 40px

    - name: testimony_style
      type: divider

    - name: font
      type: typography
      label: Text Font

    - name: text_color
      type: color

    - name: name_style
      type: divider

    - name: name_font
      type: typography

    - name: name_color
      type: color

    - name: designation_style
      type: divider

    - name: designation_font
      type: typography
      
    - name: designation_color
      type: color

    - name: designation_margin
      type: margin

    - name: image_style
      type: divider

    - name: image_style
      type: select
      value: square
      lable: Image Style 
      options:
        img-square : Square
        img-rounded: Rounded 
        img-circle : Circle

    - name: image_margin
      type: margin 
      label: Margin 

    - name: nav_style
      type: divider

    - name: nav_color
      type: color
      label: Navigation Arrow Color
      depends:
        arrows : true

    - name: dots_nav_color
      type: color
      label: Dots Navigation Color
      depends:
        dots : true