name: Button Group
slug: button-group
groups: content
form:
  general:
    - name: buttons
      type: group-repeater
      schema: 
        - name: button
          type: link

        - name: icon
          type: icon

        - name: icon_placement
          type: select
          value: left
          options:
            left: Left
            right: Right

        - name: style
          type: select
          value: qx-btn-default
          options:
            qx-btn-default: Default
            qx-btn-primary: Primary
            qx-btn-success: Success
            qx-btn-info: Info
            qx-btn-warning: Warning
            qx-btn-danger: Danger
            qx-btn-link: Link

        - name: custom_style
          type: switch
          label: Custom Style 

        - name: button_style
          type: divider
          label: Colors
          depends:
            custom_style: true

        - name: text_color
          type: color
          label: Text Color
          depends:
            custom_style: true

        - name: bg_color
          type: color
          label: Background Color
          depends:
            custom_style: true

        - name: bg_color_hover
          type: color
          label: Hover Background Color
          depends:
            custom_style: true

        - name: text_color_hover
          type: color
          label: Hover Text Color
          depends:
            custom_style: true

        - name: btn_border_style
          type: divider
          label: Border Style
          depends:
            custom_style: true

        - name: border
          type: switch
          label: Border Styling
          depends:
            custom_style: true

        - name: border_width
          type: slider
          label: Border Width
          suffix: px
          value: 2
          depends:
            border: true

        - name: border_style
          type: select
          value: solid
          depends:
            border: true
          options:
            solid: Solid
            dotted: Dotted
            dashed: Dashed
            double: Double

        - name: border_color
          type: color
          label: Border Color
          depends:
            border: true

        - name: border_hover_color
          type: color
          label: Border Hover Color
          depends:
            border: true

        - name : icon_style
          type : divider
          label: Icon Style
          depends:
            custom_style: true

        - name: button_icon_color
          type: color
          label: Icon Color
          depends:
            custom_style: true

        - name: button_icon_color_hover
          type: color
          label: Icon Hover Color
          depends:
            custom_style: true

        - name : padding_style
          type : divider
          depends:
            custom_style: true

        - name: padding
          type: padding
          depends:
            custom_style: true

      value:
        - button:
            text : Button 1
            url : 
            target:
  styles:
    - name: alignment
      type: select
      value: left
      options:
        left: Left
        center: Center
        right: Right
      image: true 
      responsive: true 

    - name: font
      type: typography

    - name: button_spacing
      type: slider
      suffix: px
      value: 10
      help: Define spacing between button

    - name : border_boxshadow
      type: divider
      label: Border & Box Shadow - All Button

    - name: border_radius
      type: slider
      label: Border Radius
      value: 0
      suffix: px 

    - name : box_shadow
      type : switch
      label : Enable Box Shadow   

    - name : box_shadow_color
      type : color 
      label : Color 
      depends:
        box_shadow : true 

    - name : box_shadow_blur
      type : slider
      label : Blur 
      max : 200
      suffix : px
      depends:
        box_shadow : true 

    - name : box_shadow_spread
      type : slider
      label : Spread 
      max : 200
      suffix : px
      depends:
        box_shadow : true  

    - name : box_shadow_horizontal
      type : slider
      label : Horizontal 
      min : -250
      max : 250
      suffix : px
      depends:
        box_shadow : true 

    - name : box_shadow_vertical
      type : slider
      label : Vertical 
      min : -250
      max : 250
      suffix : px
      depends:
        box_shadow : true 

    - name : box_shadow_inset
      type : switch 
      label : Inset 
      help : If specified, the shadows are drawn inside the frame.
      depends:
        box_shadow : true     

    - name: icon_maegin_style
      type: divider
      label: Icon Margin

    - name: icon_margin
      type: margin
      label: Icon Margin

    - name: element
      type: divider
      label: Element Style - Apply On Element Body

    - name: margin
      type: margin
