name: Counter
slug: counter
groups: pro
form:
  general:
    - name : counter_fg_element_mode
      label: Counter
      type: fields-group
      status: open
      schema:
        - name: count_start
          label: Start
          type: text
          value: 1

        - name: count_end
          label: End
          type: text
          value: 100

        - name: counter_prefix
          label: Number Prefix
          type: text
          value: 

        - name: suffix
          label: Number Suffix
          type: text
          value: 

        - name: title
          label: Title
          type: text
          value: 'Cool Number'

        - name: duration
          label: Duration
          type: text
          value: 3000

  styles:
    - name: counter_fg_number_style
      label: Number
      status: open
      type: fields-group
      schema:
        - name: number_color
          label: Color
          type: color

        - name: number_typo
          label: Font
          type: typography

        - name: number_padding
          label: Padding
          type: dimensions
          units: %, px, em, rem, vh

    - name: counter_fg_title_style
      label: Title
      type: fields-group
      schema:
        - name: title_color
          label: Color
          type: color

        - name: title_typo
          label: Font
          type: typography
  
        - name: title_padding
          label: Padding
          type: dimensions
          units: %, px, em, rem, vh