name: Custom HTML
slug: custom-html
groups:
form:
  general:
    - name: content
      type: textarea
      height: 500
      label: Enter HTML Code

    - name: prepare_content
      type: switch
      value: false
      help: Optionally prepare the content with the Joomla Content Plugins.