name: Icon List
slug: icon-list
groups: general
form:
  general:
    - name: icon_list
      type: group-repeater
      schema:
        
        - name: title
          type: text
          value: Text
          Label: List Item

        - name: link
          type: link

        - name: icon
          type: media
          filters: icon

      value:
        - title : List 1
          icon: 'libraries/quix/assets/images/placeholder.png'
        - title : List 2
          icon: 'libraries/quix/assets/images/placeholder.png'
        - title : List 3
          icon: 'libraries/quix/assets/images/placeholder.png'
        
    - name : iconlist_fg_layout
      label: Layout and Icon
      type: fields-group
      schema:
        - name: common_icon
          type: media
          filters: icon

        - name: layout
          label: Layout
          type: select
          value: vr
          options:
            vr: List
            hr: Inline

        - name : alignment
          type : choose
          label: Position
          responsive : false
          options:
            left :
              label: Left
              icon : qxuicon-align-left
            center :
              label : Center
              icon : qxuicon-align-center
            right : 
              label : Right
              icon : qxuicon-align-right
  
  style:
    - name: typography_setting
      label: Typography
      type: fields-group
      schema:
        - name: text_font
          label: Typography
          type: typography
        

    - name: spacing_setting
      label: Spacing
      type: fields-group
      schema:
        - name  : item_spacing
          label : Item Spacing
          type: slider
          units: px
          defaultUnit: px
          max : 100
          value: 
            desktop : 5
            tablet : 5
            phone : 5
        
        - name: item_padding
          label: Item Padding
          type: dimensions
          units: px
          defaultUnit: px

        - name  : text_indent
          label : Text Indent
          type: slider
          units: px
          defaultUnit: px          
          max : 100
          value: 
            desktop : 5
            tablet : 5
            phone : 5            
    
    - name: border_setting
      label: Border
      type: fields-group
      schema:
        - name: icon_border_width
          type: dimensions
          label: Width
          units: px
          defaultUnt: px

        - name: icon_border_type
          type: select
          label: Border Type      
          value: none
          options:
            none: None
            solid: Solid
            double: Double
            dotted: Dotted
            dashed: Dashed
        
        - name: icon_border_color
          type: color
          label: Border Color
        
        - name: icon_border_radius
          type: dimensions
          label: Border Radius
          units: px
          defaultUnit: px
        

    - name: color_setting
      label: Color
      type: fields-group
      schema:
        - name  : icon_hover
          label : Icon Hover Color
          type: color

        - name  : text_color
          label : Text Color
          type: color        

        - name  : text_hover
          label : Text Hover Color
          type: color        
        
