name: Soundcloud
slug: soundcloud
groups: content
form:
  general:
    - name: soundcloud
      type: textarea
      help: Paste soundcloud embeed code here.

  styles:
    - name: margin
      type: margin

    - name: padding
      type: padding