name: Line Chart
slug: chart-line
groups: Chart

form:
  general:
    - name: line-chart
      type: group-repeater
      schema:
        - name: label
          help: The label for the dataset which appears in the legend and tooltips.
          value: Coffee

        - name: data
          type: text
          label: Value
          help: Provide value for each label. It should be number. Eg. 100

      value:
        - label : Red

  styles:
    - name: enable_responsive
      type: switch
      value: true
      label: Enable Responsive

    - name: width
      type: slider
      max: 1200
      value: 300
      suffix: px
      depends:
        enable_responsive : false

    - name: height
      type: slider
      max: 1200
      value: 300
      suffix: px
      depends:
        enable_responsive : false

    - name: enable_fill
      type: switch
      value: true
      label: Fill
      help: If yes, fill the area under the line

    - name: background_color
      type: color
      label: Background Color

    - name: border_color
      type: color
      label: Border Color

    - name: pointer_style
      type: divider

    - name: point_border_color
      type: color
      label: Border Color

    - name: point_background_color
      type: color
      label: Background Color

    - name: point_hover_background_color
      type: color
      label: Hover Background Color

    - name: point_hover_border_color
      type: color
      label: Hover Border Color

    - name: show_line
      type: switch
      value: true
      label: Show Lines
      help: If no, the lines between points are not drawn

    - name: padding
      type: padding

    - name: margin
      type: margin
